# version 0.3.4
builds:
  - main: ./docubook
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: docubook
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - format: tar.gz
    # This option makes the archive name cleaner, e.g.: docubook_1.2.3_Linux_x86_64.tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

release:
  header: |
    ## Install this Version
    ```bash
    go install github.com/DocuBook/cli/docubook@{{ .Tag }}
    ```

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    # Exclude irrelevant commits from changelog -skip
    exclude:
      - '^docs:'
      - '^test:'
      - 'merge'
