# .github/workflows/release.yml
name: Go Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    # FIX: Tambahkan blok 'permissions' ini
    # Ini memberikan izin kepada Actions untuk membuat rilis.
    permissions:
      contents: write # Diperlukan untuk membuat rilis dan mengunggah aset

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
