# Nama workflow yang akan tampil di tab Actions
name: Sync Dist to DocuBook Repo

# Pemicu (trigger) workflow
on:
  push:
    branches:
      - main # Hanya berjalan saat ada push ke branch main
    paths:
      - 'npm/src/dist/**' # Hanya berjalan jika ada perubahan di dalam direktori ini

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode dari repo sumber (DocuBook/cli)
      - name: Checkout source repository
        uses: actions/checkout@v4

      # Langkah 2: Clone repo tujuan (DocuBook/docubook) menggunakan PAT
      - name: Clone destination repository
        run: |
          git clone https://x-access-token:${{ secrets.DOCUBOOK_PAT }}@github.com/DocuBook/docubook.git dev

      # Langkah 3: Sinkronisasi file dari direktori dist
      # Ganti `docubook/path/to/destination` dengan path tujuan di repo docubook
      - name: Sync files to destination
        run: |
          rsync -av --delete npm/src/dist/ dev/

      # Langkah 4: Buat commit, push, dan create Pull Request
      - name: Create Pull Request
        env:
          # Gunakan PAT untuk otentikasi GitHub CLI
          GITHUB_TOKEN: ${{ secrets.DOCUBOOK_PAT }}
        run: |
          cd dev
          
          # Konfigurasi git user
          git config user.name "Bot DocuBook"
          git config user.email "wildan@docubook.pro"
          
          # Cek apakah ada perubahan, jika tidak, hentikan proses
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
            exit 0
          fi
          
          # Buat branch baru yang unik berdasarkan SHA commit
          SOURCE_COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)
          NEW_BRANCH="dev-${SOURCE_COMMIT_SHA}"
          git checkout -b ${NEW_BRANCH}
          
          # Add, commit, dan push ke branch baru
          git add .
          git commit -m "feat(sync): Sync dist from cli@${SOURCE_COMMIT_SHA}"
          git push origin ${NEW_BRANCH}
          
          # Buat Pull Request menggunakan GitHub CLI
          gh pr create \
            --title "Sync: Update Dist from DocuBook/cli" \
            --body "Automated PR to sync changes from \`DocuBook/cli@${SOURCE_COMMIT_SHA}\`. Please review the changes." \
            --base main \
            --head ${NEW_BRANCH}