# The name of the workflow as it will appear in the Actions tab
name: Sync Dist to DocuBook Repo

# Workflow trigger
on:
  push:
    branches:
      - main
    paths:
      - 'npm/src/dist/**'

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Clone destination repository
        run: |
          git clone https://github.com/DocuBook/docubook.git dev

      - name: Sync files to destination
        run: |
          rsync -av --delete npm/src/dist/ dev/

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.DOCUBOOK_PAT }}
        run: |
          cd dev
          
          git config user.name "Bot DocuBook"
          git config user.email "wildan@docubook.pro"
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
            exit 0
          fi
          
          SOURCE_COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)
          NEW_BRANCH="dev-${SOURCE_COMMIT_SHA}"
          git checkout -b ${NEW_BRANCH}
          
          git add .
          git commit -m "feat(sync): Sync dist from cli@${SOURCE_COMMIT_SHA}"

          # =================================================================
          # NEW AUTHENTICATION METHOD
          # =================================================================
          # Override any default credential manager from the runner
          git config --unset-all credential.helper
          # Set our own credential helper that directly provides the PAT
          git config credential.helper '!f() { echo "username=x-access-token"; echo "password=${{ secrets.DOCUBOOK_PAT }}"; }; f'

          # Now push to the clean repository URL
          git push https://github.com/DocuBook/docubook.git ${NEW_BRANCH}
          
          # Create Pull Request using GitHub CLI
          gh pr create \
            --title "Sync: Update Dist from DocuBook/cli" \
            --body "Automated PR to sync changes from \`DocuBook/cli@${SOURCE_COMMIT_SHA}\`. Please review the changes." \
            --base main \
            --head ${NEW_BRANCH}