# The name of the workflow as it will appear in the Actions tab
name: Sync Dist to DocuBook Repo

# Workflow trigger
on:
  push:
    branches:
      - main
    paths:
      - 'npm/src/dist/**'

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      # Set up SSH Agent with Private Key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOCUBOOK_SSH_PRIVATE_KEY }}

      # Clone the destination repository using SSH
      - name: Clone destination repository
        run: |
          git clone git@github.com:DocuBook/docubook.git dev

      - name: Sync files to destination
        run: |
          rsync -av --delete npm/src/dist/ dev/

      - name: Create Pull Request
        # Note: 'gh pr create' still needs PAT for API authentication
        env:
          GITHUB_TOKEN: ${{ secrets.DOCUBOOK_PAT }}
        run: |
          cd dev
          
          # Configure user commit
          git config user.name "Bot DocuBook"
          git config user.email "wildan@docubook.pro"
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
            exit 0
          fi
          
          SOURCE_COMMIT_SHA=$(echo "${{ github.sha }}" | cut -c 1-7)
          NEW_BRANCH="dev-${SOURCE_COMMIT_SHA}"
          git checkout -b ${NEW_BRANCH}
          
          git add .
          git commit -m "feat(sync): Sync dist from cli@${SOURCE_COMMIT_SHA}"

          # =================================================================
          # PERUBAHAN DI SINI
          # =================================================================
          # Push explicitly to the SSH destination repository URL
          git push git@github.com:DocuBook/docubook.git ${NEW_BRANCH}
          
          # Create Pull Request using GitHub CLI
          # This uses GITHUB_TOKEN (PAT) for API interaction
          gh pr create \
            --title "Sync: Update Dist from DocuBook/cli" \
            --body "Automated PR to sync changes from \`DocuBook/cli@${SOURCE_COMMIT_SHA}\`. Please review the changes." \
            --base main \
            --head ${NEW_BRANCH}