# The name of the workflow as it will appear in the Actions tab
name: Sync Dist and Create PR (via SSH)

# Workflow trigger
on:
  push:
    branches:
      - main
    paths:
      - 'npm/src/dist/**'

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Perform a full clone, not a shallow one
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 means fetch all history

      # Step 2: Setup the SSH Agent with the Private Key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOCUBOOK_SSH_PRIVATE_KEY }}

      # Step 3: Clone the destination repository using SSH
      - name: Clone Destination Repository
        run: |
          git clone git@github.com:DocuBook/docubook.git dev

      # Step 4: Sync the files to the destination
      - name: Sync Files to Destination
        run: |
          rsync -av --delete npm/src/dist/ dev/

      # Step 5: Commit, Push, and Create Pull Request
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.DOCUBOOK_PAT }}
        run: |
          cd dev
          
          git config user.name "Bot DocuBook"
          git config user.email "wildan@docubook.pro"
          
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
            exit 0
          fi
          
          git checkout -b dev
          
          git add .
          git commit -m "feat(sync): Sync dist from cli@${{ github.sha }}"

          REMOTE_BRANCH="dev-sync-$(echo "${{ github.sha }}" | cut -c 1-7)"
          
          git push git@github.com:DocuBook/docubook.git dev:${REMOTE_BRANCH}

          # =================================================================
          # PERUBAHAN DI SINI: Tambahkan jeda 5 detik
          # =================================================================
          echo "Waiting for 5 seconds for branch to propagate..."
          sleep 5
          
          gh pr create \
            --title "Sync: Update Dist from DocuBook/cli" \
            --body "Automated PR to sync changes from \`DocuBook/cli@${{ github.sha }}\`. Please review the changes." \
            --base main \
            --head ${REMOTE_BRANCH}