# The name of the workflow as it will appear in the Actions tab
name: Sync NPM Package Version

# Workflow trigger
on:
  push:
    branches:
      - main
    paths:
      - 'npm/src/dist/**'

jobs:
  sync-from-npm:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Perform a full clone of the source repository
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 0 means fetch all history

      # Step 2: Setup the SSH Agent with the Private Key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DOCUBOOK_SSH_PRIVATE_KEY }}

      # Step 3: Clone the destination repository
      - name: Clone Destination Repository
        run: |
          git clone git@github.com:DocuBook/docubook.git dev

      # Step 4: Initialize package version
      - name: Get Package Version
        id: get_version
        run: echo "version=$(jq -r .version npm/package.json)" >> $GITHUB_OUTPUT

      # Step 5: Sync, Commit, Push, and Create Pull Request
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.DOCUBOOK_PAT }}
          PR_BODY: |
            This is an automated pull request to sync the built distributable files from the `DocuBook/cli` repository.

            ### 📦 New Version
            `v${{ steps.get_version.outputs.version }}`

            ### 🔗 Source Commit
            The changes originated from this commit in the source repository:
            [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            Please review the file changes and merge if everything looks correct.
        run: |
          cd dev
          
          # Configure the git user for the commit
          git config user.name "Bot DocuBook"
          git config user.email "wildan@docubook.pro"

          # Create a new local branch named 'dev' from the default branch
          git checkout -b dev

          # =================================================================
          # REFACTORED FILE HANDLING STARTS HERE
          # =================================================================

          # 1. Safely remove all old files from the working directory
          # This does not touch the .git directory
          git rm -rf .

          # 2. Copy the new content from the source's dist folder
          cp -r ../npm/src/dist/. .
          
          # =================================================================
          
          # Check if there are any actual changes to commit
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
            exit 0
          fi
          
          # Add and commit the new content
          git add .
          git commit -m "chore(sync): Sync package version v${{ steps.get_version.outputs.version }}"

          # Define a unique name for the remote branch
          REMOTE_BRANCH="dev-$(echo "${{ github.sha }}" | cut -c 1-7)"
          
          # Push the local 'dev' branch to the unique remote branch
          git push git@github.com:DocuBook/docubook.git dev:${REMOTE_BRANCH}
          
          # Wait a few seconds for GitHub's API to see the new branch
          echo "Waiting for 5 seconds for branch to propagate..."
          sleep 5
          
          # Create a Pull Request from the unique remote branch
          gh pr create \
            --title "chore(sync): Sync package version v${{ steps.get_version.outputs.version }}" \
            --body "$PR_BODY" \
            --base main \
            --head ${REMOTE_BRANCH}